export const DB = [
  {
    game: "Left 4 Dead 2",
    link: "https://store.steampowered.com/app/550/Left_4_Dead_2/",
    played: "Все",
    ended: "Все",
    type: "Кооператив",
  },
  {
    game: "Dead By Daylight",
    link: "https://store.steampowered.com/app/381210/Dead_by_Daylight/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Counter Strike: Global Offensive",
    link: "https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/",
    played: "Все",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Human: Fall Flat",
    link: "https://store.steampowered.com/app/477160/Human_Fall_Flat/",
    played: "Все",
    ended: "МБ, МГ, АП, АЮ ",
    type: "Кооператив",
  },
  {
    game: "We Were Here",
    link: "https://store.steampowered.com/app/582500/We_Were_Here/",
    played: "МБ, АЮ",
    ended: "МБ, АЮ",
    type: "Кооператив",
  },
  {
    game: "We Were Here Too",
    link: "https://store.steampowered.com/app/677160/We_Were_Here_Too/",
    played: "МБ, АЮ",
    ended: "МБ, АЮ",
    type: "Кооператив",
  },
  {
    game: "We Were Here Together",
    link: "https://store.steampowered.com/app/865360/We_Were_Here_Together/",
    played: "МБ, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Rust",
    link: "https://store.steampowered.com/app/252490/Rust/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Saints Row: The Third",
    link: "https://store.steampowered.com/app/55230/Saints_Row_The_Third/",
    played: "МБ, АЮ",
    ended: "МБ",
    type: "Кооператив",
  },
  {
    game: "Saints Row IV",
    link: "https://store.steampowered.com/app/206420/Saints_Row_IV/",
    played: "МБ, АЮ",
    ended: "МБ",
    type: "Кооператив",
  },
  {
    game: "Deep Rock Galactic",
    link: "https://store.steampowered.com/app/548430/Deep_Rock_Galactic/",
    played: "Все",
    ended: "-",
    type: "Кооператив",
  },
  {
    game: "Grand Theft Auto 5",
    link: "https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/",
    played: "Все",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Chivalry: Medieval Warfare",
    link: "https://store.steampowered.com/app/219640/Chivalry_Medieval_Warfare/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Battlefield 3",
    link: "https://www.origin.com/rus/ru-ru/store/battlefield/battlefield-3",
    played: "МБ, АР, АЮ",
    ended: "",
    type: "Мультиплеер",
  },
  {
    game: "Call Of Duty: Black Ops II - Zombies",
    link: "https://store.steampowered.com/app/202970/Call_of_Duty_Black_Ops_II/",
    played: "МБ, АП, АР, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Payday 2",
    link: "https://store.steampowered.com/app/218620/PAYDAY_2/",
    played: "Все",
    ended: "-",
    type: "Кооператив",
  },
  {
    game: "Borderlands 2",
    link: "https://store.steampowered.com/app/49520/Borderlands_2/",
    played: "МБ, АП, АР, АЮ",
    ended: "МБ, АП, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Dying Light",
    link: "https://store.steampowered.com/app/239140/Dying_Light/",
    played: "МБ, АР",
    ended: "МБ",
    type: "Кооператив",
  },
  {
    game: "Mortal Kombat 9",
    link: "https://store.steampowered.com/app/237110/Mortal_Kombat_Komplete_Edition/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Terraria",
    link: "https://store.steampowered.com/app/105600/Terraria/",
    played: "МБ, МГ, АР, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "7 Days To Die",
    link: "https://store.steampowered.com/app/251570/7_Days_to_Die/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Кооператив",
  },
  {
    game: "The Forest",
    link: "https://store.steampowered.com/app/242760/The_Forest/",
    played: "МБ, МГ, АР, АЮ",
    ended: "МБ, МГ, АР, АЮ ",
    type: "Кооператив",
  },
  {
    game: "The Darkness 2",
    link: "https://store.steampowered.com/app/67370/The_Darkness_II/",
    played: "МБ, АР, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Quake Champions",
    link: "https://store.steampowered.com/app/611500/Quake_Champions/",
    played: "Все",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Tom Clancy's Splinter Cell Blacklist",
    link: "https://store.steampowered.com/app/235600/Tom_Clancys_Splinter_Cell_Blacklist/",
    played: "МБ, АР",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Warhammer: Vermintide 2",
    link: "https://store.steampowered.com/app/552500/Warhammer_Vermintide_2/",
    played: "МБ, АР, АЮ",
    ended: "МБ, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Sniper Elite: Nazi Zombie Army 2",
    link: "https://store.steampowered.com/app/247910/Sniper_Elite_Nazi_Zombie_Army_2/",
    played: "МБ, АР, АЮ",
    ended: "МБ, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Serious Sam 3: BFE",
    link: "https://store.steampowered.com/app/41070/Serious_Sam_3_BFE/",
    played: "МБ, АР, АЮ",
    ended: "МБ, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Broforce",
    link: "https://store.steampowered.com/app/274190/Broforce/",
    played: "МБ, АЮ",
    ended: "МБ",
    type: "Кооператив",
  },
  {
    game: "Strange Brigade",
    link: "https://store.steampowered.com/app/312670/Strange_Brigade/",
    played: "МБ, МГ, АР, АЮ",
    ended: "МБ, МГ, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Spec Ops: The Line",
    link: "https://store.steampowered.com/app/50300/Spec_Ops_The_Line/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Depth",
    link: "https://store.steampowered.com/app/274940/Depth/",
    played: "МБ, МГ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Sniper Ghost Warrior 2",
    link: "https://store.steampowered.com/app/34870/Sniper_Ghost_Warrior_2/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Injustice: Gods Among Us",
    link: "https://store.steampowered.com/app/242700/Injustice_Gods_Among_Us_Ultimate_Edition/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Gauntlet",
    link: "https://store.steampowered.com/app/258970/Gauntlet_Slayer_Edition/",
    played: "МБ, АЮ",
    ended: "МБ, АЮ  ",
    type: "Кооператив",
  },
  {
    game: "Zombie Army Trilogy",
    link: "https://store.steampowered.com/app/301640/Zombie_Army_Trilogy/",
    played: "МБ, МГ, АР, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "A Way Out",
    link: "https://store.steampowered.com/app/1222700/A_Way_Out/",
    played: "МБ, АР",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Rake",
    link: "https://store.steampowered.com/app/386880/Rake/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Neverwinter",
    link: "https://store.steampowered.com/app/109600/Neverwinter/",
    played: "МБ, МГ, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "World Of Warcraft",
    link: "https://worldofwarcraft.com/ru-ru/",
    played: "МБ, МГ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Point Blank",
    link: "https://ru.4game.com/pointblank/",
    played: "МБ, МГ, AР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Warface",
    link: "https://ru.warface.com/",
    played: "МБ, МГ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Contagion",
    link: "https://store.steampowered.com/app/238430/Contagion/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Nether: Resurrected",
    link: "https://store.steampowered.com/app/247730/Nether_Resurrected/",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Rocket League",
    link: "https://store.steampowered.com/app/252950/Rocket_League/",
    played: "МБ, АП, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Brawlhalla",
    link: "https://store.steampowered.com/app/291550/Brawlhalla/",
    played: "МБ, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "The Elder Scrolls Online",
    link: "https://store.steampowered.com/app/306130/The_Elder_Scrolls_Online/",
    played: "МБ, АЮ",
    ended: "-",
    type: "Кооператив, Мультиплеер",
  },
  {
    game: "Divinity: Original Sin",
    link: "https://store.steampowered.com/app/373420/Divinity_Original_Sin__Enhanced_Edition/",
    played: "АР, АЮ / МБ, АЮ",
    ended: "АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Astroneer",
    link: "https://store.steampowered.com/app/361420/ASTRONEER/",
    played: "АП, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Castle Crashers",
    link: "https://store.steampowered.com/app/204360/Castle_Crashers/",
    played: "МБ, АР, АЮ",
    ended: "МБ, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Ark: Survival Evolved",
    link: "https://store.steampowered.com/app/346110/ARK_Survival_Evolved/",
    played: "МГ, АР",
    ended: "-",
    type: "Кооператив, Мультиплеер",
  },
  {
    game: "Raft",
    link: "https://store.steampowered.com/app/648800/Raft/",
    played: "АП, АР",
    ended: "АП",
    type: "Кооператив",
  },
  {
    game: "Borderlands: The Pre-Sequel",
    link: "https://store.steampowered.com/app/261640/Borderlands_The_PreSequel/",
    played: "",
    ended: "",
    type: "Кооператив"
  },
  {
    game: "Gang Beasts",
    link: "https://store.steampowered.com/app/261640/Borderlands_The_PreSequel/",
    played: "",
    ended: "",
    type: "Мультиплеер"
  },
  {
    game: "Kingdom Two Crowns",
    link: "https://store.steampowered.com/app/261640/Borderlands_The_PreSequel/",
    played: "",
    ended: "",
    type: "Мультиплеер"
  }
];
