export const DB = [
  {
    game: "Left 4 Dead 2",
    played: "Все",
    ended: "Все",
    type: "Кооператив",
  },
  {
    game: "Dead By Daylight",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Counter Strike: Global Offensive",
    played: "Все",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Human: Fall Flat",
    played: "Все",
    ended: "МБ, МГ, АП, АЮ ",
    type: "Кооператив",
  },
  {
    game: "We Were Here",
    played: "МБ, АЮ",
    ended: "МБ, АЮ",
    type: "Кооператив",
  },
  {
    game: "We Were Here Too",
    played: "МБ, АЮ",
    ended: "МБ, АЮ",
    type: "Кооператив",
  },
  {
    game: "We Were Here Together",
    played: "МБ, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Rust",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Saints Row: The Third",
    played: "МБ, АЮ",
    ended: "МБ",
    type: "Кооператив",
  },
  {
    game: "Saints Row IV",
    played: "МБ, АЮ",
    ended: "МБ",
    type: "Кооператив",
  },
  {
    game: "Deep Rock Galactic",
    played: "Все",
    ended: "-",
    type: "Кооператив",
  },
  {
    game: "Grand Theft Auto 5",
    played: "Все",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Chivalry: Medieval Warfare",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Battlefield 3",
    played: "МБ, АР, АЮ",
    ended: "",
    type: "Мультиплеер",
  },
  {
    game: "Call Of Duty: Black Ops II - Zombies",
    played: "МБ, АП, АР, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Payday 2",
    played: "Все",
    ended: "-",
    type: "Кооператив",
  },
  {
    game: "Borderlands 2",
    played: "МБ, АП, АР, АЮ",
    ended: "МБ, АП, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Dying Light",
    played: "МБ, АР",
    ended: "МБ",
    type: "Кооператив",
  },
  {
    game: "Mortal Kombat 9",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Terraria",
    played: "МБ, МГ, АР, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "7 Days To Die",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Кооператив",
  },
  {
    game: "The Forest",
    played: "МБ, МГ, АР, АЮ",
    ended: "МБ, МГ, АР, АЮ ",
    type: "Кооператив",
  },
  {
    game: "The Darkness 2",
    played: "МБ, АР, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Quake Champions",
    played: "Все",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Tom Clancy's Splinter Cell Blacklist",
    played: "МБ, АР",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Warhammer: Vermintide 2",
    played: "МБ, АР, АЮ",
    ended: "МБ, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Sniper Elite: Nazi Zombie Army",
    played: "МБ, АР, АЮ",
    ended: "МБ, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Serious Sam 3: BFE",
    played: "МБ, АР, АЮ",
    ended: "МБ, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Broforce",
    played: "МБ, АЮ",
    ended: "МБ",
    type: "Кооператив",
  },
  {
    game: "Strange Brigade",
    played: "МБ, МГ, АР, АЮ",
    ended: "МБ, МГ, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Spec Ops: The Line",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Depth",
    played: "МБ, МГ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Sniper Ghost Warrior 2",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Injustice: Gods Among Us",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Gauntlet",
    played: "МБ, АЮ",
    ended: "МБ, АЮ  ",
    type: "Кооператив",
  },
  {
    game: "Zombie Army Trilogy",
    played: "МБ, МГ, АР, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "A Way Out",
    played: "МБ, АР",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Rake",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Neverwinter",
    played: "МБ, МГ, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "World Of Warkraft",
    played: "МБ, МГ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Point Blank",
    played: "МБ, МГ, AР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Warface",
    played: "МБ, МГ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Contagion",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Nether",
    played: "МБ, АР, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Rocket League",
    played: "",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "Brawhalla",
    played: "МБ, АЮ",
    ended: "-",
    type: "Мультиплеер",
  },
  {
    game: "The Elder Scrolls Online",
    played: "МБ, АЮ",
    ended: "-",
    type: "Кооператив, Мультиплеер",
  },
  {
    game: "Divinity: Original Sin",
    played: "АР, АЮ / МБ, АЮ",
    ended: "АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Astroneer",
    played: "АП, АЮ",
    ended: "",
    type: "Кооператив",
  },
  {
    game: "Castle Crashers",
    played: "МБ, АР, АЮ",
    ended: "МБ, АР, АЮ",
    type: "Кооператив",
  },
  {
    game: "Ark: Survival Evolved",
    played: "МГ, АР",
    ended: "-",
    type: "Кооператив, Мультиплеер",
  },
  {
    game: "Raft",
    played: "АП, АР",
    ended: "АП",
    type: "Кооператив",
  },
  {
    game: "Borderlands: The Pre-Sequel",
    played: "",
    ended: "",
    type: "Кооператив"
  },
  // {
  //   game: "",
  //   played: "",
  //   ended: "",
  //   type: ""
  // },
];
